export const AIRPORTS = [
  { code: "JFK", city: "New York" },
  { code: "LAX", city: "Los Angeles" },
  { code: "ORD", city: "Chicago" },
  { code: "ATL", city: "Atlanta" },
  { code: "DFW", city: "Dallas" },
  { code: "SFO", city: "San Francisco" },
  { code: "SEA", city: "Seattle" },
  { code: "YYZ", city: "Toronto" },
  { code: "YVR", city: "Vancouver" },
  { code: "MEX", city: "Mexico City" },
  { code: "LHR", city: "London" },
  { code: "LGW", city: "London" },
  { code: "CDG", city: "Paris" },
  { code: "ORY", city: "Paris" },
  { code: "AMS", city: "Amsterdam" },
  { code: "FRA", city: "Frankfurt" },
  { code: "MUC", city: "Munich" },
  { code: "MAD", city: "Madrid" },
  { code: "BCN", city: "Barcelona" },
  { code: "FCO", city: "Rome" },
  { code: "MXP", city: "Milan" },
  { code: "ZRH", city: "Zurich" },
  { code: "VIE", city: "Vienna" },
  { code: "IST", city: "Istanbul" },
  { code: "CPH", city: "Copenhagen" },
  { code: "ARN", city: "Stockholm" },
  { code: "OSL", city: "Oslo" },
  { code: "HEL", city: "Helsinki" },
  { code: "DXB", city: "Dubai" },
  { code: "DWC", city: "Dubai" },
  { code: "AUH", city: "Abu Dhabi" },
  { code: "DOH", city: "Doha" },
  { code: "RUH", city: "Riyadh" },
  { code: "JED", city: "Jeddah" },
  { code: "AMM", city: "Amman" },
  { code: "BEY", city: "Beirut" },
  { code: "TLV", city: "Tel Aviv" },
  { code: "KWI", city: "Kuwait City" },
  { code: "HND", city: "Tokyo" },
  { code: "NRT", city: "Tokyo" },
  { code: "ICN", city: "Seoul" },
  { code: "PEK", city: "Beijing" },
  { code: "PVG", city: "Shanghai" },
  { code: "HKG", city: "Hong Kong" },
  { code: "SIN", city: "Singapore" },
  { code: "BKK", city: "Bangkok" },
  { code: "KUL", city: "Kuala Lumpur" },
  { code: "DEL", city: "New Delhi" },
  { code: "BOM", city: "Mumbai" },
  { code: "CAI", city: "Cairo" },
  { code: "JNB", city: "Johannesburg" },
  { code: "CPT", city: "Cape Town" },
  { code: "ADD", city: "Addis Ababa" },
  { code: "CMN", city: "Casablanca" },
  { code: "SYD", city: "Sydney" },
  { code: "MEL", city: "Melbourne" },
  { code: "AKL", city: "Auckland" }
];
