export const Airlines: Record<string, string> = {
  KU: "Kuwait Airways",
  XY: "flynas",
  SV: "Saudia",
  EK: "Emirates",
  QR: "Qatar Airways",
  EY: "Etihad Airways",
  GF: "Gulf Air",
  WY: "Oman Air",
  MH: "Malaysia Airlines",
  QF: "Qantas Airways",
  SQ: "Singapore Airlines",
  AI: "Air India",
  TG: "Thai Airways",
  VN: "Vietnam Airlines",
  BA: "British Airways",
  CX: "Cathay Pacific",
  JL: "Japan Airlines",
  AA: "American Airlines",
  DL: "Delta Air Lines",
  RJ: "Royal Jordanian",
  D8: "AirAsia X",
  MS: "EgyptAir",
  ME: "Middle East Airlines",
  J9: "Jazeera Airways",
  FZ: "flydubai",
  G9: "Air Arabia",
  AH: "Air Algérie",
  LH: "Lufthansa",
  AF: "Air France",
  KL: "KLM Royal Dutch Airlines",
  LX: "SWISS International Air Lines",
  AZ: "ITA Airways",
  IB: "Iberia",
  TP: "TAP Air Portugal",
  LO: "LOT Polish Airlines",
  OS: "Austrian Airlines",
  SK: "Scandinavian Airlines",
  SN: "Brussels Airlines",
  FR: "Ryanair",
  PC: "Pegasus Airlines",
  JU: "Air Serbia",
  QS: "Smartwings",
  BT: "Air Baltic",
  LG: "Lufthansa Cargo",
  TU: "Tunisair",
  OK: "Czech Airlines",
  U2: "easyJet",
  W6: "Wizz Air",
  F3: "Vueling Airlines",
  VY: "Vueling",
  TK: "Turkish Airlines",
  NH: "All Nippon Airways",
  UA: "United Airlines",
  AC: "Air Canada",
  WS: "WestJet",
  B6: "JetBlue Airways",
  NZ: "Air New Zealand",
  ET: "Ethiopian Airlines",
  AT: "Royal Air Maroc",
  KQ: "Kenya Airways",
  J2: "Azerbaijan Airlines",
  AY: "Finnair",
  EW: "Eurowings",
  VS: "Virgin Atlantic",
  A3: "Aegean Airlines",
  AS: "Alaska Airlines",
  CA: "Air China",
  PR: "Philippine Airlines",
  LY: "EL AL Israel Airlines",
  MU: "China Eastern Airlines",
  "6X": "Air Odisha",
};
