export const Airlines: Record<string, string> = {
  KU: "Kuwait Airways",
  XY: "flynas",
  SV: "Saudia",
  EK: "Emirates",
  QR: "Qatar Airways",
  EY: "Etihad Airways",
  GF: "Gulf Air",
  WY: "Oman Air",
  RJ: "Royal Jordanian",
  MS: "EgyptAir",
  ME: "Middle East Airlines",
  J9: "Jazeera Airways",
  FZ: "flydubai",
  G9: "Air Arabia",
  AH: "Air Algérie",
  LH: "Lufthansa",
  AF: "Air France",
  KL: "KLM Royal Dutch Airlines",
  BA: "British Airways",
  LX: "SWISS International Air Lines",
  AZ: "ITA Airways",
  IB: "Iberia",
  TP: "TAP Air Portugal",
  LO: "LOT Polish Airlines",
  OS: "Austrian Airlines",
  SK: "Scandinavian Airlines",
  SN: "Brussels Airlines",
  FR: "Ryanair",
  U2: "easyJet",
  W6: "Wizz Air",
  F3: "Vueling Airlines",
  VY: "Vueling",
  

  TK: "Turkish Airlines",
  SQ: "Singapore Airlines",
  CX: "Cathay Pacific",
  NH: "All Nippon Airways",
  JL: "Japan Airlines",

  AA: "American Airlines",
  DL: "Delta Air Lines",
  UA: "United Airlines",
  AC: "Air Canada",

  ET: "Ethiopian Airlines",
  AT: "Royal Air Maroc",
  KQ: "Kenya Airways",
  J2: "Azerbaijan Airlines",
  AY: "Finnair",
  EW: "Eurowings",
  VS: "Virgin Atlantic",
  A3: "Aegean Airlines",
  AI: "Air India",
  AS: "Alaska Airlines",
  CA: "Air China",
  PR: "Philippine Airlines",
  LY: "EL AL Israel Airlines",
  MU: "China Eastern Airlines",
  "6X": "Air Odisha",
};
